In [4]:
import numpy as np 

In [5]:
# help(np)

In [6]:
# Si ce n'est pas installé il faut taper la ligne de commande suivante

# pip install numpy

In [8]:
# print(np.sctypes)

In [10]:
a = np.array([1, 2, np.nan])

In [11]:
a.dtype

dtype('float64')

In [12]:
# a[0] = "Bonjour" 

ValueError: could not convert string to float: 'Bonjour'

In [13]:
a[0] = 100

In [14]:
a

array([100.,   2.,  nan])

In [17]:
b = np.array(["Big data", "Python", "Pandas"])

In [18]:
b.dtype

dtype('<U8')

In [19]:
b[0]

'Big data'

In [20]:
b[0] = 'Le big data est top' 

In [21]:
b

array(['Le big d', 'Python', 'Pandas'], dtype='<U8')

In [25]:
d = np.array(["Big data", "Python", "Pandas"], dtype='<U28')

In [26]:
d[0] = 'Le big data est top' 

In [27]:
d

array(['Le big data est top', 'Python', 'Pandas'], dtype='<U28')

In [28]:
dt = np.dtype([
    ('name', np.dtype('U14')), ('grades', np.float64) 
])

In [29]:
dt

dtype([('name', '<U14'), ('grades', '<f8')])

In [30]:
dataset = np.array([
      ( "Luce du Coulon" , 12.5),
      ( "Auguste Dupont", 8.5),
      ( "Roger Le Voisi", 1.5)
], dtype=dt)

In [31]:
dataset.dtype

dtype([('name', '<U14'), ('grades', '<f8')])

In [32]:
dataset

array([('Luce du Coulon', 12.5), ('Auguste Dupont',  8.5),
       ('Roger Le Voisi',  1.5)],
      dtype=[('name', '<U14'), ('grades', '<f8')])

In [46]:
notes = np.array( [ n for c, n in dataset ], dtype=np.float32)

In [47]:
notes.sum()

22.5

In [48]:
notes.dtype

dtype('float32')

In [41]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.longdouble],
 'complex': [numpy.complex64, numpy.complex128, numpy.clongdouble],
 'others': [bool, object, bytes, str, numpy.void]}

In [51]:
"""
for k in np.sctypes:
    print( k, np.sctypes[k] )
    print()
"""
print("info sur les types" )

info sur les types


In [53]:
z = np.zeros(3)

In [54]:
z.dtype

dtype('float64')

In [55]:
z

array([0., 0., 0.])

In [56]:
z[0] = 1_000_000

In [57]:
z

array([1000000.,       0.,       0.])

In [59]:
# Tableau 6 lignes et 2 colonnes
tmp = np.empty((6, 2), dtype='float32')

In [60]:
tmp

array([[2.1122846e+08, 3.0738883e-41],
       [0.0000000e+00, 0.0000000e+00],
       [1.5974802e-43, 4.4841551e-44],
       [1.0649868e-43, 1.4153114e-43],
       [4.4841551e-44, 1.2051167e-43],
       [1.5554413e-43, 1.4713634e-43]], dtype=float32)

In [62]:
z = np.zeros(10)

In [63]:
numbers = np.array( [ n for n in range(1, 11) ])

In [64]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Exercice 

Ajoutez au tableau z 2 quand le nombre est paire et 1 quand il est impaire respectivement pour les valeurs de numbers.


In [66]:
for i, number in enumerate(numbers):
    if number % 2 : 
        z[i] = 1
    else:
        z[i] = 2

print(z)

[1. 2. 1. 2. 1. 2. 1. 2. 1. 2.]


In [67]:
z = np.zeros(10)

change = lambda n : 2 if n % 2 else 1

# Initialiser un tableau numpy z avec des zéros
numbers = np.array( [ n for n in range(1, 11) ] )

# Définir une fonction lambda (par exemple, doubler chaque élément)
change = np.vectorize(lambda n : 2. if n % 2 else 1.)

# Appliquer la fonction lambda au tableau z
resultat = change(numbers)

# Afficher le résultat
print(resultat)

In [144]:
# Attention le code ci-dessous crée une matrice avec des valeurs aléatoires
# m = np.random.randint(10, size=(10,10))

m = np.array([[4, 3, 8, 5, 2, 2, 0, 1, 8, 6],
       [1, 7, 6, 2, 7, 0, 1, 6, 1, 1],
       [7, 2, 8, 0, 8, 2, 5, 8, 3, 7],
       [6, 5, 7, 8, 2, 2, 2, 9, 2, 3],
       [6, 4, 3, 6, 6, 6, 9, 5, 8, 2],
       [0, 2, 9, 0, 4, 5, 3, 4, 0, 1],
       [0, 3, 5, 1, 4, 6, 0, 4, 5, 6],
       [0, 3, 5, 7, 4, 9, 3, 7, 4, 8],
       [1, 3, 1, 2, 9, 4, 4, 9, 5, 4],
       [6, 5, 0, 0, 1, 7, 9, 0, 9, 5]])

In [145]:
m

array([[4, 3, 8, 5, 2, 2, 0, 1, 8, 6],
       [1, 7, 6, 2, 7, 0, 1, 6, 1, 1],
       [7, 2, 8, 0, 8, 2, 5, 8, 3, 7],
       [6, 5, 7, 8, 2, 2, 2, 9, 2, 3],
       [6, 4, 3, 6, 6, 6, 9, 5, 8, 2],
       [0, 2, 9, 0, 4, 5, 3, 4, 0, 1],
       [0, 3, 5, 1, 4, 6, 0, 4, 5, 6],
       [0, 3, 5, 7, 4, 9, 3, 7, 4, 8],
       [1, 3, 1, 2, 9, 4, 4, 9, 5, 4],
       [6, 5, 0, 0, 1, 7, 9, 0, 9, 5]])

Exercice 

1. Calculez la somme des valeurs en colonne.
1. Calculez la somme des valeurs en ligne.
1. Calculez la somme des valeurs en diagonale.

```python
data = np.array([[4, 3, 8, 5, 2, 2, 0, 1, 8, 6],
       [1, 7, 6, 2, 7, 0, 1, 6, 1, 1],
       [7, 2, 8, 0, 8, 2, 5, 8, 3, 7],
       [6, 5, 7, 8, 2, 2, 2, 9, 2, 3],
       [6, 4, 3, 6, 6, 6, 9, 5, 8, 2],
       [0, 2, 9, 0, 4, 5, 3, 4, 0, 1],
       [0, 3, 5, 1, 4, 6, 0, 4, 5, 6],
       [0, 3, 5, 7, 4, 9, 3, 7, 4, 8],
       [1, 3, 1, 2, 9, 4, 4, 9, 5, 4],
       [6, 5, 0, 0, 1, 7, 9, 0, 9, 5]])
```


In [146]:
# somme total des lignes et colonne
m.sum()

418

In [147]:
# Somme des colonnes
sc = np.sum(m, axis=0)
print(sc)
# Somme des lignes
sr = np.sum(m, axis=1)
print(sr)

[31 37 52 31 47 43 36 53 45 43]
[39 32 50 46 55 28 34 50 42 42]


In [148]:
# trace
np.trace(m)

55

In [149]:
m

array([[4, 3, 8, 5, 2, 2, 0, 1, 8, 6],
       [1, 7, 6, 2, 7, 0, 1, 6, 1, 1],
       [7, 2, 8, 0, 8, 2, 5, 8, 3, 7],
       [6, 5, 7, 8, 2, 2, 2, 9, 2, 3],
       [6, 4, 3, 6, 6, 6, 9, 5, 8, 2],
       [0, 2, 9, 0, 4, 5, 3, 4, 0, 1],
       [0, 3, 5, 1, 4, 6, 0, 4, 5, 6],
       [0, 3, 5, 7, 4, 9, 3, 7, 4, 8],
       [1, 3, 1, 2, 9, 4, 4, 9, 5, 4],
       [6, 5, 0, 0, 1, 7, 9, 0, 9, 5]])

In [150]:
np.trace( m )

55

In [151]:
# approche slicing
np.trace( m[::-1] )

42

Exercice

Pour la matrice m ci-dessus.

1. Faites la somme des lignes paires.
1. Créez une nouvelle matrice en élimimant les lignes dont la somme est pair.

In [152]:
sr = np.sum(m[::2], axis=1)

In [153]:
# sommes des lignes paires
print(sr)
# somme totale des lignes
print( sr.sum() )

# pour le total on peut aller plus vite 
total = np.sum(m[::2], axis=1).sum()
print(total)

[39 50 55 34 42]
220
220


In [154]:
"""
Rappel pour préciser les axes dans les sommes 
axis = 0 colonnes et axis = 1 les lignes
"""

mtest = np.array( [ [1, 2] , [ 8, 19 ] ] ) 

# somme des lignes
print(np.sum(mtest, axis=1) )
# somme des colonnes
print(np.sum(mtest, axis=0) )

[ 3 27]
[ 9 21]


In [155]:
sums = np.sum(m, axis=1)
mask = sums % 2 == 0 
# s'appliquera par ligne 
print( mask )
m[ mask ]

[False  True  True  True False  True  True  True  True  True]


array([[1, 7, 6, 2, 7, 0, 1, 6, 1, 1],
       [7, 2, 8, 0, 8, 2, 5, 8, 3, 7],
       [6, 5, 7, 8, 2, 2, 2, 9, 2, 3],
       [0, 2, 9, 0, 4, 5, 3, 4, 0, 1],
       [0, 3, 5, 1, 4, 6, 0, 4, 5, 6],
       [0, 3, 5, 7, 4, 9, 3, 7, 4, 8],
       [1, 3, 1, 2, 9, 4, 4, 9, 5, 4],
       [6, 5, 0, 0, 1, 7, 9, 0, 9, 5]])

In [123]:
m

array([[4, 3, 8, 5, 2, 2, 0, 1, 8, 6],
       [1, 7, 6, 2, 7, 0, 1, 6, 1, 1],
       [7, 2, 8, 0, 8, 2, 5, 8, 3, 7],
       [6, 5, 7, 8, 2, 2, 2, 9, 2, 3],
       [6, 4, 3, 6, 6, 6, 9, 5, 8, 2],
       [0, 2, 9, 0, 4, 5, 3, 4, 0, 1],
       [0, 3, 5, 1, 4, 6, 0, 4, 5, 6],
       [0, 3, 5, 7, 4, 9, 3, 7, 4, 8],
       [1, 3, 1, 2, 9, 4, 4, 9, 5, 4],
       [6, 5, 0, 0, 1, 7, 9, 0, 9, 5]])

In [156]:
# dimension 3
m3 = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

In [157]:
m3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

Exercice
1. Faites la somme de la première et la dernière matrice.
1. Faites la somme la deuxième colonne de chaque matrice.
1. Faites la somme des deux derniers nombres de la deuxième colonne de chaque matrice.

In [159]:
# 1.
total = (m3[0] + m3[-1::]).sum()

432

In [161]:
# 2.
m3[:, : , 1].sum()

216

In [162]:
# 3.
m3[:, -2::, 1].sum()

153